from typing import Optional

from System import ConsoleColor


class IOProvider: ...


class BasicTerminalEmulator: ...


class NavigableTerminalEmulator(BasicTerminalEmulator):
    def __init__(self, io: IOProvider, forceVCursor: bool = False): ...
    def WriteRaw(self, text: str, color: Optional[ConsoleColor] = None): ...
    def NewLine(self): ...
